### ISSUE TITLE
Error in running

### ISSUE THREAD

**Issue by amin3mej** [siyanew/pylalala#1]
Hi, 
First at all, thanks for publishing the code. I tried to run the code but i got some errors. These are the logs:

Python 3: 
```
▶ python3 lalala.py



Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/playsound.py", line 55, in _playsoundOSX
    from AppKit     import NSSound
ModuleNotFoundError: No module named 'AppKit'
```

Python 2: 
``` 
▶ python lalala.py
  File "lalala.py", line 10
SyntaxError: Non-ASCII character '\xf0' in file lalala.py on line 10, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by siyanew** [comment]
Hi @amin3mej ,

I think it is because of some dependency issue in playsound module. Installing pyobjc may solve it. 
`sudo pip install pyobjc`.

**Comment by amin3mej** [comment]
Thanks for your fast response. The error gone.

Can you mark this issue as "Resolved"?
